<?php

use Illuminate\Database\Seeder;
use Illuminate\Database\Eloquent\Model;

class CountryTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('countries')->truncate();
        $countries = array(
            array("timezone"=>"+04:30","region"=>"Asia","subregion"=>"Southern Asia","name"=>"Afghanistan","alpha2Code"=>"AF","alpha3Code"=>"AFG"),
            array("timezone"=>"+02:00","region"=>"Europe","subregion"=>"Northern Europe","name"=>"Åland Islands","alpha2Code"=>"AX","alpha3Code"=>"ALA"),
            array("timezone"=>"+01:00","region"=>"Europe","subregion"=>"Southern Europe","name"=>"Albania","alpha2Code"=>"AL","alpha3Code"=>"ALB"),
            array("timezone"=>"+01:00","region"=>"Africa","subregion"=>"Northern Africa","name"=>"Algeria","alpha2Code"=>"DZ","alpha3Code"=>"DZA"),
            array("timezone"=>"-11:00","region"=>"Oceania","subregion"=>"Polynesia","name"=>"American Samoa","alpha2Code"=>"AS","alpha3Code"=>"ASM"),
            array("timezone"=>"+01:00","region"=>"Europe","subregion"=>"Southern Europe","name"=>"Andorra","alpha2Code"=>"AD","alpha3Code"=>"AND"),
            array("timezone"=>"+01:00","region"=>"Africa","subregion"=>"Middle Africa","name"=>"Angola","alpha2Code"=>"AO","alpha3Code"=>"AGO"),
            array("timezone"=>"-04:00","region"=>"Americas","subregion"=>"Caribbean","name"=>"Anguilla","alpha2Code"=>"AI","alpha3Code"=>"AIA"),
            array("timezone"=>"-03:00","region"=>"Polar","subregion"=>"","name"=>"Antarctica","alpha2Code"=>"AQ","alpha3Code"=>"ATA"),
            array("timezone"=>"-04:00","region"=>"Americas","subregion"=>"Caribbean","name"=>"Antigua and Barbuda","alpha2Code"=>"AG","alpha3Code"=>"ATG"),
            array("timezone"=>"-03:00","region"=>"Americas","subregion"=>"South America","name"=>"Argentina","alpha2Code"=>"AR","alpha3Code"=>"ARG"),
            array("timezone"=>"+04:00","region"=>"Asia","subregion"=>"Western Asia","name"=>"Armenia","alpha2Code"=>"AM","alpha3Code"=>"ARM"),
            array("timezone"=>"-04:00","region"=>"Americas","subregion"=>"Caribbean","name"=>"Aruba","alpha2Code"=>"AW","alpha3Code"=>"ABW"),
            array("timezone"=>"+05:00","region"=>"Oceania","subregion"=>"Australia and New Zealand","name"=>"Australia","alpha2Code"=>"AU","alpha3Code"=>"AUS"),
            array("timezone"=>"+01:00","region"=>"Europe","subregion"=>"Western Europe","name"=>"Austria","alpha2Code"=>"AT","alpha3Code"=>"AUT"),
            array("timezone"=>"+04:00","region"=>"Asia","subregion"=>"Western Asia","name"=>"Azerbaijan","alpha2Code"=>"AZ","alpha3Code"=>"AZE"),
            array("timezone"=>"-05:00","region"=>"Americas","subregion"=>"Caribbean","name"=>"The Bahamas","alpha2Code"=>"BS","alpha3Code"=>"BHS"),
            array("timezone"=>"+03:00","region"=>"Asia","subregion"=>"Western Asia","name"=>"Bahrain","alpha2Code"=>"BH","alpha3Code"=>"BHR"),
            array("timezone"=>"+06:00","region"=>"Asia","subregion"=>"Southern Asia","name"=>"Bangladesh","alpha2Code"=>"BD","alpha3Code"=>"BGD"),
            array("timezone"=>"-04:00","region"=>"Americas","subregion"=>"Caribbean","name"=>"Barbados","alpha2Code"=>"BB","alpha3Code"=>"BRB"),
            array("timezone"=>"+03:00","region"=>"Europe","subregion"=>"Eastern Europe","name"=>"Belarus","alpha2Code"=>"BY","alpha3Code"=>"BLR"),
            array("timezone"=>"+01:00","region"=>"Europe","subregion"=>"Western Europe","name"=>"Belgium","alpha2Code"=>"BE","alpha3Code"=>"BEL"),
            array("timezone"=>"-06:00","region"=>"Americas","subregion"=>"Central America","name"=>"Belize","alpha2Code"=>"BZ","alpha3Code"=>"BLZ"),
            array("timezone"=>"+01:00","region"=>"Africa","subregion"=>"Western Africa","name"=>"Benin","alpha2Code"=>"BJ","alpha3Code"=>"BEN"),
            array("timezone"=>"-04:00","region"=>"Americas","subregion"=>"Northern America","name"=>"Bermuda","alpha2Code"=>"BM","alpha3Code"=>"BMU"),
            array("timezone"=>"+06:00","region"=>"Asia","subregion"=>"Southern Asia","name"=>"Bhutan","alpha2Code"=>"BT","alpha3Code"=>"BTN"),
            array("timezone"=>"-04:00","region"=>"Americas","subregion"=>"South America","name"=>"Bolivia","alpha2Code"=>"BO","alpha3Code"=>"BOL"),
            array("timezone"=>"-04:00","region"=>"Americas","subregion"=>"Caribbean","name"=>"Bonaire","alpha2Code"=>"BQ","alpha3Code"=>"BES"),
            array("timezone"=>"+01:00","region"=>"Europe","subregion"=>"Southern Europe","name"=>"Bosnia and Herzegovina","alpha2Code"=>"BA","alpha3Code"=>"BIH"),
            array("timezone"=>"+02:00","region"=>"Africa","subregion"=>"Southern Africa","name"=>"Botswana","alpha2Code"=>"BW","alpha3Code"=>"BWA"),
            array("timezone"=>"+01:00","region"=>"","subregion"=>"","name"=>"Bouvet Island","alpha2Code"=>"BV","alpha3Code"=>"BVT"),
            array("timezone"=>"-05:00","region"=>"Americas","subregion"=>"South America","name"=>"Brazil","alpha2Code"=>"BR","alpha3Code"=>"BRA"),
            array("timezone"=>"+06:00","region"=>"Africa","subregion"=>"Eastern Africa","name"=>"British Indian Ocean Territory","alpha2Code"=>"IO","alpha3Code"=>"IOT"),
            array("timezone"=>"-11:00","region"=>"Americas","subregion"=>"Northern America","name"=>"United States Minor Outlying Islands","alpha2Code"=>"UM","alpha3Code"=>"UMI"),
            array("timezone"=>"-04:00","region"=>"Americas","subregion"=>"Caribbean","name"=>"Virgin Islands (British)","alpha2Code"=>"VG","alpha3Code"=>"VGB"),
            array("timezone"=>"-04:00","region"=>"Americas","subregion"=>"Caribbean","name"=>"Virgin Islands (U.S.)","alpha2Code"=>"VI","alpha3Code"=>"VIR"),
            array("timezone"=>"+08:00","region"=>"Asia","subregion"=>"South-Eastern Asia","name"=>"Brunei","alpha2Code"=>"BN","alpha3Code"=>"BRN"),
            array("timezone"=>"+02:00","region"=>"Europe","subregion"=>"Eastern Europe","name"=>"Bulgaria","alpha2Code"=>"BG","alpha3Code"=>"BGR"),
            array("timezone"=>"+00:00","region"=>"Africa","subregion"=>"Western Africa","name"=>"Burkina Faso","alpha2Code"=>"BF","alpha3Code"=>"BFA"),
            array("timezone"=>"+02:00","region"=>"Africa","subregion"=>"Eastern Africa","name"=>"Burundi","alpha2Code"=>"BI","alpha3Code"=>"BDI"),
            array("timezone"=>"+07:00","region"=>"Asia","subregion"=>"South-Eastern Asia","name"=>"Cambodia","alpha2Code"=>"KH","alpha3Code"=>"KHM"),
            array("timezone"=>"+01:00","region"=>"Africa","subregion"=>"Middle Africa","name"=>"Cameroon","alpha2Code"=>"CM","alpha3Code"=>"CMR"),
            array("timezone"=>"-08:00","region"=>"Americas","subregion"=>"Northern America","name"=>"Canada","alpha2Code"=>"CA","alpha3Code"=>"CAN"),
            array("timezone"=>"-01:00","region"=>"Africa","subregion"=>"Western Africa","name"=>"Cape Verde","alpha2Code"=>"CV","alpha3Code"=>"CPV"),
            array("timezone"=>"-05:00","region"=>"Americas","subregion"=>"Caribbean","name"=>"Cayman Islands","alpha2Code"=>"KY","alpha3Code"=>"CYM"),
            array("timezone"=>"+01:00","region"=>"Africa","subregion"=>"Middle Africa","name"=>"Central African Republic","alpha2Code"=>"CF","alpha3Code"=>"CAF"),
            array("timezone"=>"+01:00","region"=>"Africa","subregion"=>"Middle Africa","name"=>"Chad","alpha2Code"=>"TD","alpha3Code"=>"TCD"),
            array("timezone"=>"-06:00","region"=>"Americas","subregion"=>"South America","name"=>"Chile","alpha2Code"=>"CL","alpha3Code"=>"CHL"),
            array("timezone"=>"+08:00","region"=>"Asia","subregion"=>"Eastern Asia","name"=>"China","alpha2Code"=>"CN","alpha3Code"=>"CHN"),
            array("timezone"=>"+07:00","region"=>"Oceania","subregion"=>"Australia and New Zealand","name"=>"Christmas Island","alpha2Code"=>"CX","alpha3Code"=>"CXR"),
            array("timezone"=>"+06:30","region"=>"Oceania","subregion"=>"Australia and New Zealand","name"=>"Cocos (Keeling) Islands","alpha2Code"=>"CC","alpha3Code"=>"CCK"),
            array("timezone"=>"-05:00","region"=>"Americas","subregion"=>"South America","name"=>"Colombia","alpha2Code"=>"CO","alpha3Code"=>"COL"),
            array("timezone"=>"+03:00","region"=>"Africa","subregion"=>"Eastern Africa","name"=>"Comoros","alpha2Code"=>"KM","alpha3Code"=>"COM"),
            array("timezone"=>"+01:00","region"=>"Africa","subregion"=>"Middle Africa","name"=>"Republic of the Congo","alpha2Code"=>"CG","alpha3Code"=>"COG"),
            array("timezone"=>"+01:00","region"=>"Africa","subregion"=>"Middle Africa","name"=>"Democratic Republic of the Congo","alpha2Code"=>"CD","alpha3Code"=>"COD"),
            array("timezone"=>"-10:00","region"=>"Oceania","subregion"=>"Polynesia","name"=>"Cook Islands","alpha2Code"=>"CK","alpha3Code"=>"COK"),
            array("timezone"=>"-06:00","region"=>"Americas","subregion"=>"Central America","name"=>"Costa Rica","alpha2Code"=>"CR","alpha3Code"=>"CRI"),
            array("timezone"=>"+01:00","region"=>"Europe","subregion"=>"Southern Europe","name"=>"Croatia","alpha2Code"=>"HR","alpha3Code"=>"HRV"),
            array("timezone"=>"-05:00","region"=>"Americas","subregion"=>"Caribbean","name"=>"Cuba","alpha2Code"=>"CU","alpha3Code"=>"CUB"),
            array("timezone"=>"-04:00","region"=>"Americas","subregion"=>"Caribbean","name"=>"Curaçao","alpha2Code"=>"CW","alpha3Code"=>"CUW"),
            array("timezone"=>"+02:00","region"=>"Europe","subregion"=>"Southern Europe","name"=>"Cyprus","alpha2Code"=>"CY","alpha3Code"=>"CYP"),
            array("timezone"=>"+01:00","region"=>"Europe","subregion"=>"Eastern Europe","name"=>"Czech Republic","alpha2Code"=>"CZ","alpha3Code"=>"CZE"),
            array("timezone"=>"-04:00","region"=>"Europe","subregion"=>"Northern Europe","name"=>"Denmark","alpha2Code"=>"DK","alpha3Code"=>"DNK"),
            array("timezone"=>"+03:00","region"=>"Africa","subregion"=>"Eastern Africa","name"=>"Djibouti","alpha2Code"=>"DJ","alpha3Code"=>"DJI"),
            array("timezone"=>"-04:00","region"=>"Americas","subregion"=>"Caribbean","name"=>"Dominica","alpha2Code"=>"DM","alpha3Code"=>"DMA"),
            array("timezone"=>"-04:00","region"=>"Americas","subregion"=>"Caribbean","name"=>"Dominican Republic","alpha2Code"=>"DO","alpha3Code"=>"DOM"),
            array("timezone"=>"-06:00","region"=>"Americas","subregion"=>"South America","name"=>"Ecuador","alpha2Code"=>"EC","alpha3Code"=>"ECU"),
            array("timezone"=>"+02:00","region"=>"Africa","subregion"=>"Northern Africa","name"=>"Egypt","alpha2Code"=>"EG","alpha3Code"=>"EGY"),
            array("timezone"=>"-06:00","region"=>"Americas","subregion"=>"Central America","name"=>"El Salvador","alpha2Code"=>"SV","alpha3Code"=>"SLV"),
            array("timezone"=>"+01:00","region"=>"Africa","subregion"=>"Middle Africa","name"=>"Equatorial Guinea","alpha2Code"=>"GQ","alpha3Code"=>"GNQ"),
            array("timezone"=>"+03:00","region"=>"Africa","subregion"=>"Eastern Africa","name"=>"Eritrea","alpha2Code"=>"ER","alpha3Code"=>"ERI"),
            array("timezone"=>"+02:00","region"=>"Europe","subregion"=>"Northern Europe","name"=>"Estonia","alpha2Code"=>"EE","alpha3Code"=>"EST"),
            array("timezone"=>"+03:00","region"=>"Africa","subregion"=>"Eastern Africa","name"=>"Ethiopia","alpha2Code"=>"ET","alpha3Code"=>"ETH"),
            array("timezone"=>"-04:00","region"=>"Americas","subregion"=>"South America","name"=>"Falkland Islands","alpha2Code"=>"FK","alpha3Code"=>"FLK"),
            array("timezone"=>"+00:00","region"=>"Europe","subregion"=>"Northern Europe","name"=>"Faroe Islands","alpha2Code"=>"FO","alpha3Code"=>"FRO"),
            array("timezone"=>"+12:00","region"=>"Oceania","subregion"=>"Melanesia","name"=>"Fiji","alpha2Code"=>"FJ","alpha3Code"=>"FJI"),
            array("timezone"=>"+02:00","region"=>"Europe","subregion"=>"Northern Europe","name"=>"Finland","alpha2Code"=>"FI","alpha3Code"=>"FIN"),
            array("timezone"=>"-10:00","region"=>"Europe","subregion"=>"Western Europe","name"=>"France","alpha2Code"=>"FR","alpha3Code"=>"FRA"),
            array("timezone"=>"-03:00","region"=>"Americas","subregion"=>"South America","name"=>"French Guiana","alpha2Code"=>"GF","alpha3Code"=>"GUF"),
            array("timezone"=>"-10:00","region"=>"Oceania","subregion"=>"Polynesia","name"=>"French Polynesia","alpha2Code"=>"PF","alpha3Code"=>"PYF"),
            array("timezone"=>"+05:00","region"=>"Africa","subregion"=>"Southern Africa","name"=>"French Southern and Antarctic Lands","alpha2Code"=>"TF","alpha3Code"=>"ATF"),
            array("timezone"=>"+01:00","region"=>"Africa","subregion"=>"Middle Africa","name"=>"Gabon","alpha2Code"=>"GA","alpha3Code"=>"GAB"),
            array("timezone"=>"+00:00","region"=>"Africa","subregion"=>"Western Africa","name"=>"The Gambia","alpha2Code"=>"GM","alpha3Code"=>"GMB"),
            array("timezone"=>"-05:00","region"=>"Asia","subregion"=>"Western Asia","name"=>"Georgia","alpha2Code"=>"GE","alpha3Code"=>"GEO"),
            array("timezone"=>"+01:00","region"=>"Europe","subregion"=>"Western Europe","name"=>"Germany","alpha2Code"=>"DE","alpha3Code"=>"DEU"),
            array("timezone"=>"+00:00","region"=>"Africa","subregion"=>"Western Africa","name"=>"Ghana","alpha2Code"=>"GH","alpha3Code"=>"GHA"),
            array("timezone"=>"+01:00","region"=>"Europe","subregion"=>"Southern Europe","name"=>"Gibraltar","alpha2Code"=>"GI","alpha3Code"=>"GIB"),
            array("timezone"=>"+02:00","region"=>"Europe","subregion"=>"Southern Europe","name"=>"Greece","alpha2Code"=>"GR","alpha3Code"=>"GRC"),
            array("timezone"=>"-04:00","region"=>"Americas","subregion"=>"Northern America","name"=>"Greenland","alpha2Code"=>"GL","alpha3Code"=>"GRL"),
            array("timezone"=>"-04:00","region"=>"Americas","subregion"=>"Caribbean","name"=>"Grenada","alpha2Code"=>"GD","alpha3Code"=>"GRD"),
            array("timezone"=>"-04:00","region"=>"Americas","subregion"=>"Caribbean","name"=>"Guadeloupe","alpha2Code"=>"GP","alpha3Code"=>"GLP"),
            array("timezone"=>"+10:00","region"=>"Oceania","subregion"=>"Micronesia","name"=>"Guam","alpha2Code"=>"GU","alpha3Code"=>"GUM"),
            array("timezone"=>"-06:00","region"=>"Americas","subregion"=>"Central America","name"=>"Guatemala","alpha2Code"=>"GT","alpha3Code"=>"GTM"),
            array("timezone"=>"+00:00","region"=>"Europe","subregion"=>"Northern Europe","name"=>"Guernsey","alpha2Code"=>"GG","alpha3Code"=>"GGY"),
            array("timezone"=>"+00:00","region"=>"Africa","subregion"=>"Western Africa","name"=>"Guinea","alpha2Code"=>"GN","alpha3Code"=>"GIN"),
            array("timezone"=>"+00:00","region"=>"Africa","subregion"=>"Western Africa","name"=>"Guinea-Bissau","alpha2Code"=>"GW","alpha3Code"=>"GNB"),
            array("timezone"=>"-04:00","region"=>"Americas","subregion"=>"South America","name"=>"Guyana","alpha2Code"=>"GY","alpha3Code"=>"GUY"),
            array("timezone"=>"-05:00","region"=>"Americas","subregion"=>"Caribbean","name"=>"Haiti","alpha2Code"=>"HT","alpha3Code"=>"HTI"),
            array("timezone"=>"+05:00","region"=>"","subregion"=>"","name"=>"Heard Island and McDonald Islands","alpha2Code"=>"HM","alpha3Code"=>"HMD"),
            array("timezone"=>"+01:00","region"=>"Europe","subregion"=>"Southern Europe","name"=>"Holy See","alpha2Code"=>"VA","alpha3Code"=>"VAT"),
            array("timezone"=>"-06:00","region"=>"Americas","subregion"=>"Central America","name"=>"Honduras","alpha2Code"=>"HN","alpha3Code"=>"HND"),
            array("timezone"=>"+08:00","region"=>"Asia","subregion"=>"Eastern Asia","name"=>"Hong Kong","alpha2Code"=>"HK","alpha3Code"=>"HKG"),
            array("timezone"=>"+01:00","region"=>"Europe","subregion"=>"Eastern Europe","name"=>"Hungary","alpha2Code"=>"HU","alpha3Code"=>"HUN"),
            array("timezone"=>"+00:00","region"=>"Europe","subregion"=>"Northern Europe","name"=>"Iceland","alpha2Code"=>"IS","alpha3Code"=>"ISL"),
            array("timezone"=>"+05:30","region"=>"Asia","subregion"=>"Southern Asia","name"=>"India","alpha2Code"=>"IN","alpha3Code"=>"IND"),
            array("timezone"=>"+07:00","region"=>"Asia","subregion"=>"South-Eastern Asia","name"=>"Indonesia","alpha2Code"=>"ID","alpha3Code"=>"IDN"),
            array("timezone"=>"+00:00","region"=>"Africa","subregion"=>"Western Africa","name"=>"Ivory Coast","alpha2Code"=>"CI","alpha3Code"=>"CIV"),
            array("timezone"=>"+03:30","region"=>"Asia","subregion"=>"Southern Asia","name"=>"Iran","alpha2Code"=>"IR","alpha3Code"=>"IRN"),
            array("timezone"=>"+03:00","region"=>"Asia","subregion"=>"Western Asia","name"=>"Iraq","alpha2Code"=>"IQ","alpha3Code"=>"IRQ"),
            array("timezone"=>"+00:00","region"=>"Europe","subregion"=>"Northern Europe","name"=>"Republic of Ireland","alpha2Code"=>"IE","alpha3Code"=>"IRL"),
            array("timezone"=>"+00:00","region"=>"Europe","subregion"=>"Northern Europe","name"=>"Isle of Man","alpha2Code"=>"IM","alpha3Code"=>"IMN"),
            array("timezone"=>"+02:00","region"=>"Asia","subregion"=>"Western Asia","name"=>"Israel","alpha2Code"=>"IL","alpha3Code"=>"ISR"),
            array("timezone"=>"+01:00","region"=>"Europe","subregion"=>"Southern Europe","name"=>"Italy","alpha2Code"=>"IT","alpha3Code"=>"ITA"),
            array("timezone"=>"-05:00","region"=>"Americas","subregion"=>"Caribbean","name"=>"Jamaica","alpha2Code"=>"JM","alpha3Code"=>"JAM"),
            array("timezone"=>"+09:00","region"=>"Asia","subregion"=>"Eastern Asia","name"=>"Japan","alpha2Code"=>"JP","alpha3Code"=>"JPN"),
            array("timezone"=>"+01:00","region"=>"Europe","subregion"=>"Northern Europe","name"=>"Jersey","alpha2Code"=>"JE","alpha3Code"=>"JEY"),
            array("timezone"=>"+03:00","region"=>"Asia","subregion"=>"Western Asia","name"=>"Jordan","alpha2Code"=>"JO","alpha3Code"=>"JOR"),
            array("timezone"=>"+05:00","region"=>"Asia","subregion"=>"Central Asia","name"=>"Kazakhstan","alpha2Code"=>"KZ","alpha3Code"=>"KAZ"),
            array("timezone"=>"+03:00","region"=>"Africa","subregion"=>"Eastern Africa","name"=>"Kenya","alpha2Code"=>"KE","alpha3Code"=>"KEN"),
            array("timezone"=>"+12:00","region"=>"Oceania","subregion"=>"Micronesia","name"=>"Kiribati","alpha2Code"=>"KI","alpha3Code"=>"KIR"),
            array("timezone"=>"+03:00","region"=>"Asia","subregion"=>"Western Asia","name"=>"Kuwait","alpha2Code"=>"KW","alpha3Code"=>"KWT"),
            array("timezone"=>"+06:00","region"=>"Asia","subregion"=>"Central Asia","name"=>"Kyrgyzstan","alpha2Code"=>"KG","alpha3Code"=>"KGZ"),
            array("timezone"=>"+07:00","region"=>"Asia","subregion"=>"South-Eastern Asia","name"=>"Laos","alpha2Code"=>"LA","alpha3Code"=>"LAO"),
            array("timezone"=>"+02:00","region"=>"Europe","subregion"=>"Northern Europe","name"=>"Latvia","alpha2Code"=>"LV","alpha3Code"=>"LVA"),
            array("timezone"=>"+02:00","region"=>"Asia","subregion"=>"Western Asia","name"=>"Lebanon","alpha2Code"=>"LB","alpha3Code"=>"LBN"),
            array("timezone"=>"+02:00","region"=>"Africa","subregion"=>"Southern Africa","name"=>"Lesotho","alpha2Code"=>"LS","alpha3Code"=>"LSO"),
            array("timezone"=>"+00:00","region"=>"Africa","subregion"=>"Western Africa","name"=>"Liberia","alpha2Code"=>"LR","alpha3Code"=>"LBR"),
            array("timezone"=>"+01:00","region"=>"Africa","subregion"=>"Northern Africa","name"=>"Libya","alpha2Code"=>"LY","alpha3Code"=>"LBY"),
            array("timezone"=>"+01:00","region"=>"Europe","subregion"=>"Western Europe","name"=>"Liechtenstein","alpha2Code"=>"LI","alpha3Code"=>"LIE"),
            array("timezone"=>"+02:00","region"=>"Europe","subregion"=>"Northern Europe","name"=>"Lithuania","alpha2Code"=>"LT","alpha3Code"=>"LTU"),
            array("timezone"=>"+01:00","region"=>"Europe","subregion"=>"Western Europe","name"=>"Luxembourg","alpha2Code"=>"LU","alpha3Code"=>"LUX"),
            array("timezone"=>"+08:00","region"=>"Asia","subregion"=>"Eastern Asia","name"=>"Macau","alpha2Code"=>"MO","alpha3Code"=>"MAC"),
            array("timezone"=>"+01:00","region"=>"Europe","subregion"=>"Southern Europe","name"=>"Republic of Macedonia","alpha2Code"=>"MK","alpha3Code"=>"MKD"),
            array("timezone"=>"+03:00","region"=>"Africa","subregion"=>"Eastern Africa","name"=>"Madagascar","alpha2Code"=>"MG","alpha3Code"=>"MDG"),
            array("timezone"=>"+02:00","region"=>"Africa","subregion"=>"Eastern Africa","name"=>"Malawi","alpha2Code"=>"MW","alpha3Code"=>"MWI"),
            array("timezone"=>"+08:00","region"=>"Asia","subregion"=>"South-Eastern Asia","name"=>"Malaysia","alpha2Code"=>"MY","alpha3Code"=>"MYS"),
            array("timezone"=>"+05:00","region"=>"Asia","subregion"=>"Southern Asia","name"=>"Maldives","alpha2Code"=>"MV","alpha3Code"=>"MDV"),
            array("timezone"=>"+00:00","region"=>"Africa","subregion"=>"Western Africa","name"=>"Mali","alpha2Code"=>"ML","alpha3Code"=>"MLI"),
            array("timezone"=>"+01:00","region"=>"Europe","subregion"=>"Southern Europe","name"=>"Malta","alpha2Code"=>"MT","alpha3Code"=>"MLT"),
            array("timezone"=>"+12:00","region"=>"Oceania","subregion"=>"Micronesia","name"=>"Marshall Islands","alpha2Code"=>"MH","alpha3Code"=>"MHL"),
            array("timezone"=>"-04:00","region"=>"Americas","subregion"=>"Caribbean","name"=>"Martinique","alpha2Code"=>"MQ","alpha3Code"=>"MTQ"),
            array("timezone"=>"+00:00","region"=>"Africa","subregion"=>"Western Africa","name"=>"Mauritania","alpha2Code"=>"MR","alpha3Code"=>"MRT"),
            array("timezone"=>"+04:00","region"=>"Africa","subregion"=>"Eastern Africa","name"=>"Mauritius","alpha2Code"=>"MU","alpha3Code"=>"MUS"),
            array("timezone"=>"+03:00","region"=>"Africa","subregion"=>"Eastern Africa","name"=>"Mayotte","alpha2Code"=>"YT","alpha3Code"=>"MYT"),
            array("timezone"=>"-08:00","region"=>"Americas","subregion"=>"Central America","name"=>"Mexico","alpha2Code"=>"MX","alpha3Code"=>"MEX"),
            array("timezone"=>"+10:00","region"=>"Oceania","subregion"=>"Micronesia","name"=>"Federated States of Micronesia","alpha2Code"=>"FM","alpha3Code"=>"FSM"),
            array("timezone"=>"+02:00","region"=>"Europe","subregion"=>"Eastern Europe","name"=>"Moldova","alpha2Code"=>"MD","alpha3Code"=>"MDA"),
            array("timezone"=>"+01:00","region"=>"Europe","subregion"=>"Western Europe","name"=>"Monaco","alpha2Code"=>"MC","alpha3Code"=>"MCO"),
            array("timezone"=>"+07:00","region"=>"Asia","subregion"=>"Eastern Asia","name"=>"Mongolia","alpha2Code"=>"MN","alpha3Code"=>"MNG"),
            array("timezone"=>"+01:00","region"=>"Europe","subregion"=>"Southern Europe","name"=>"Montenegro","alpha2Code"=>"ME","alpha3Code"=>"MNE"),
            array("timezone"=>"-04:00","region"=>"Americas","subregion"=>"Caribbean","name"=>"Montserrat","alpha2Code"=>"MS","alpha3Code"=>"MSR"),
            array("timezone"=>"+00:00","region"=>"Africa","subregion"=>"Northern Africa","name"=>"Morocco","alpha2Code"=>"MA","alpha3Code"=>"MAR"),
            array("timezone"=>"+02:00","region"=>"Africa","subregion"=>"Eastern Africa","name"=>"Mozambique","alpha2Code"=>"MZ","alpha3Code"=>"MOZ"),
            array("timezone"=>"+06:30","region"=>"Asia","subregion"=>"South-Eastern Asia","name"=>"Myanmar","alpha2Code"=>"MM","alpha3Code"=>"MMR"),
            array("timezone"=>"+01:00","region"=>"Africa","subregion"=>"Southern Africa","name"=>"Namibia","alpha2Code"=>"NA","alpha3Code"=>"NAM"),
            array("timezone"=>"+12:00","region"=>"Oceania","subregion"=>"Micronesia","name"=>"Nauru","alpha2Code"=>"NR","alpha3Code"=>"NRU"),
            array("timezone"=>"+05:45","region"=>"Asia","subregion"=>"Southern Asia","name"=>"Nepal","alpha2Code"=>"NP","alpha3Code"=>"NPL"),
            array("timezone"=>"-04:00","region"=>"Europe","subregion"=>"Western Europe","name"=>"Netherlands","alpha2Code"=>"NL","alpha3Code"=>"NLD"),
            array("timezone"=>"+11:00","region"=>"Oceania","subregion"=>"Melanesia","name"=>"New Caledonia","alpha2Code"=>"NC","alpha3Code"=>"NCL"),
            array("timezone"=>"-11:00","region"=>"Oceania","subregion"=>"Australia and New Zealand","name"=>"New Zealand","alpha2Code"=>"NZ","alpha3Code"=>"NZL"),
            array("timezone"=>"-06:00","region"=>"Americas","subregion"=>"Central America","name"=>"Nicaragua","alpha2Code"=>"NI","alpha3Code"=>"NIC"),
            array("timezone"=>"+01:00","region"=>"Africa","subregion"=>"Western Africa","name"=>"Niger","alpha2Code"=>"NE","alpha3Code"=>"NER"),
            array("timezone"=>"+01:00","region"=>"Africa","subregion"=>"Western Africa","name"=>"Nigeria","alpha2Code"=>"NG","alpha3Code"=>"NGA"),
            array("timezone"=>"-11:00","region"=>"Oceania","subregion"=>"Polynesia","name"=>"Niue","alpha2Code"=>"NU","alpha3Code"=>"NIU"),
            array("timezone"=>"+11:30","region"=>"Oceania","subregion"=>"Australia and New Zealand","name"=>"Norfolk Island","alpha2Code"=>"NF","alpha3Code"=>"NFK"),
            array("timezone"=>"+09:00","region"=>"Asia","subregion"=>"Eastern Asia","name"=>"North Korea","alpha2Code"=>"KP","alpha3Code"=>"PRK"),
            array("timezone"=>"+10:00","region"=>"Oceania","subregion"=>"Micronesia","name"=>"Northern Mariana Islands","alpha2Code"=>"MP","alpha3Code"=>"MNP"),
            array("timezone"=>"+01:00","region"=>"Europe","subregion"=>"Northern Europe","name"=>"Norway","alpha2Code"=>"NO","alpha3Code"=>"NOR"),
            array("timezone"=>"+04:00","region"=>"Asia","subregion"=>"Western Asia","name"=>"Oman","alpha2Code"=>"OM","alpha3Code"=>"OMN"),
            array("timezone"=>"+05:00","region"=>"Asia","subregion"=>"Southern Asia","name"=>"Pakistan","alpha2Code"=>"PK","alpha3Code"=>"PAK"),
            array("timezone"=>"+09:00","region"=>"Oceania","subregion"=>"Micronesia","name"=>"Palau","alpha2Code"=>"PW","alpha3Code"=>"PLW"),
            array("timezone"=>"+02:00","region"=>"Asia","subregion"=>"Western Asia","name"=>"Palestine","alpha2Code"=>"PS","alpha3Code"=>"PSE"),
            array("timezone"=>"-05:00","region"=>"Americas","subregion"=>"Central America","name"=>"Panama","alpha2Code"=>"PA","alpha3Code"=>"PAN"),
            array("timezone"=>"+10:00","region"=>"Oceania","subregion"=>"Melanesia","name"=>"Papua New Guinea","alpha2Code"=>"PG","alpha3Code"=>"PNG"),
            array("timezone"=>"-04:00","region"=>"Americas","subregion"=>"South America","name"=>"Paraguay","alpha2Code"=>"PY","alpha3Code"=>"PRY"),
            array("timezone"=>"-05:00","region"=>"Americas","subregion"=>"South America","name"=>"Peru","alpha2Code"=>"PE","alpha3Code"=>"PER"),
            array("timezone"=>"+08:00","region"=>"Asia","subregion"=>"South-Eastern Asia","name"=>"Philippines","alpha2Code"=>"PH","alpha3Code"=>"PHL"),
            array("timezone"=>"-08:00","region"=>"Oceania","subregion"=>"Polynesia","name"=>"Pitcairn Islands","alpha2Code"=>"PN","alpha3Code"=>"PCN"),
            array("timezone"=>"+01:00","region"=>"Europe","subregion"=>"Eastern Europe","name"=>"Poland","alpha2Code"=>"PL","alpha3Code"=>"POL"),
            array("timezone"=>"-01:00","region"=>"Europe","subregion"=>"Southern Europe","name"=>"Portugal","alpha2Code"=>"PT","alpha3Code"=>"PRT"),
            array("timezone"=>"-04:00","region"=>"Americas","subregion"=>"Caribbean","name"=>"Puerto Rico","alpha2Code"=>"PR","alpha3Code"=>"PRI"),
            array("timezone"=>"+03:00","region"=>"Asia","subregion"=>"Western Asia","name"=>"Qatar","alpha2Code"=>"QA","alpha3Code"=>"QAT"),
            array("timezone"=>"+01:00","region"=>"Europe","subregion"=>"Eastern Europe","name"=>"Republic of Kosovo","alpha2Code"=>"XK","alpha3Code"=>"KOS"),
            array("timezone"=>"+04:00","region"=>"Africa","subregion"=>"Eastern Africa","name"=>"Réunion","alpha2Code"=>"RE","alpha3Code"=>"REU"),
            array("timezone"=>"+02:00","region"=>"Europe","subregion"=>"Eastern Europe","name"=>"Romania","alpha2Code"=>"RO","alpha3Code"=>"ROU"),
            array("timezone"=>"+03:00","region"=>"Europe","subregion"=>"Eastern Europe","name"=>"Russia","alpha2Code"=>"RU","alpha3Code"=>"RUS"),
            array("timezone"=>"+02:00","region"=>"Africa","subregion"=>"Eastern Africa","name"=>"Rwanda","alpha2Code"=>"RW","alpha3Code"=>"RWA"),
            array("timezone"=>"-04:00","region"=>"Americas","subregion"=>"Caribbean","name"=>"Saint Barthélemy","alpha2Code"=>"BL","alpha3Code"=>"BLM"),
            array("timezone"=>"+00:00","region"=>"Africa","subregion"=>"Western Africa","name"=>"Saint Helena","alpha2Code"=>"SH","alpha3Code"=>"SHN"),
            array("timezone"=>"-04:00","region"=>"Americas","subregion"=>"Caribbean","name"=>"Saint Kitts and Nevis","alpha2Code"=>"KN","alpha3Code"=>"KNA"),
            array("timezone"=>"-04:00","region"=>"Americas","subregion"=>"Caribbean","name"=>"Saint Lucia","alpha2Code"=>"LC","alpha3Code"=>"LCA"),
            array("timezone"=>"-04:00","region"=>"Americas","subregion"=>"Caribbean","name"=>"Saint Martin","alpha2Code"=>"MF","alpha3Code"=>"MAF"),
            array("timezone"=>"-03:00","region"=>"Americas","subregion"=>"Northern America","name"=>"Saint Pierre and Miquelon","alpha2Code"=>"PM","alpha3Code"=>"SPM"),
            array("timezone"=>"-04:00","region"=>"Americas","subregion"=>"Caribbean","name"=>"Saint Vincent and the Grenadines","alpha2Code"=>"VC","alpha3Code"=>"VCT"),
            array("timezone"=>"+13:00","region"=>"Oceania","subregion"=>"Polynesia","name"=>"Samoa","alpha2Code"=>"WS","alpha3Code"=>"WSM"),
            array("timezone"=>"+01:00","region"=>"Europe","subregion"=>"Southern Europe","name"=>"San Marino","alpha2Code"=>"SM","alpha3Code"=>"SMR"),
            array("timezone"=>"+00:00","region"=>"Africa","subregion"=>"Middle Africa","name"=>"São Tomé and Príncipe","alpha2Code"=>"ST","alpha3Code"=>"STP"),
            array("timezone"=>"+03:00","region"=>"Asia","subregion"=>"Western Asia","name"=>"Saudi Arabia","alpha2Code"=>"SA","alpha3Code"=>"SAU"),
            array("timezone"=>"+00:00","region"=>"Africa","subregion"=>"Western Africa","name"=>"Senegal","alpha2Code"=>"SN","alpha3Code"=>"SEN"),
            array("timezone"=>"+01:00","region"=>"Europe","subregion"=>"Southern Europe","name"=>"Serbia","alpha2Code"=>"RS","alpha3Code"=>"SRB"),
            array("timezone"=>"+04:00","region"=>"Africa","subregion"=>"Eastern Africa","name"=>"Seychelles","alpha2Code"=>"SC","alpha3Code"=>"SYC"),
            array("timezone"=>"+00:00","region"=>"Africa","subregion"=>"Western Africa","name"=>"Sierra Leone","alpha2Code"=>"SL","alpha3Code"=>"SLE"),
            array("timezone"=>"+08:00","region"=>"Asia","subregion"=>"South-Eastern Asia","name"=>"Singapore","alpha2Code"=>"SG","alpha3Code"=>"SGP"),
            array("timezone"=>"-04:00","region"=>"Americas","subregion"=>"Caribbean","name"=>"Sint Maarten","alpha2Code"=>"SX","alpha3Code"=>"SXM"),
            array("timezone"=>"+01:00","region"=>"Europe","subregion"=>"Eastern Europe","name"=>"Slovakia","alpha2Code"=>"SK","alpha3Code"=>"SVK"),
            array("timezone"=>"+01:00","region"=>"Europe","subregion"=>"Southern Europe","name"=>"Slovenia","alpha2Code"=>"SI","alpha3Code"=>"SVN"),
            array("timezone"=>"+11:00","region"=>"Oceania","subregion"=>"Melanesia","name"=>"Solomon Islands","alpha2Code"=>"SB","alpha3Code"=>"SLB"),
            array("timezone"=>"+03:00","region"=>"Africa","subregion"=>"Eastern Africa","name"=>"Somalia","alpha2Code"=>"SO","alpha3Code"=>"SOM"),
            array("timezone"=>"+02:00","region"=>"Africa","subregion"=>"Southern Africa","name"=>"South Africa","alpha2Code"=>"ZA","alpha3Code"=>"ZAF"),
            array("timezone"=>"-02:00","region"=>"Americas","subregion"=>"South America","name"=>"South Georgia","alpha2Code"=>"GS","alpha3Code"=>"SGS"),
            array("timezone"=>"+09:00","region"=>"Asia","subregion"=>"Eastern Asia","name"=>"South Korea","alpha2Code"=>"KR","alpha3Code"=>"KOR"),
            array("timezone"=>"+03:00","region"=>"Africa","subregion"=>"Middle Africa","name"=>"South Sudan","alpha2Code"=>"SS","alpha3Code"=>"SSD"),
            array("timezone"=>"+00:00","region"=>"Europe","subregion"=>"Southern Europe","name"=>"Spain","alpha2Code"=>"ES","alpha3Code"=>"ESP"),
            array("timezone"=>"+05:30","region"=>"Asia","subregion"=>"Southern Asia","name"=>"Sri Lanka","alpha2Code"=>"LK","alpha3Code"=>"LKA"),
            array("timezone"=>"+03:00","region"=>"Africa","subregion"=>"Northern Africa","name"=>"Sudan","alpha2Code"=>"SD","alpha3Code"=>"SDN"),
            array("timezone"=>"-03:00","region"=>"Americas","subregion"=>"South America","name"=>"Suriname","alpha2Code"=>"SR","alpha3Code"=>"SUR"),
            array("timezone"=>"+01:00","region"=>"Europe","subregion"=>"Northern Europe","name"=>"Svalbard and Jan Mayen","alpha2Code"=>"SJ","alpha3Code"=>"SJM"),
            array("timezone"=>"+02:00","region"=>"Africa","subregion"=>"Southern Africa","name"=>"Swaziland","alpha2Code"=>"SZ","alpha3Code"=>"SWZ"),
            array("timezone"=>"+01:00","region"=>"Europe","subregion"=>"Northern Europe","name"=>"Sweden","alpha2Code"=>"SE","alpha3Code"=>"SWE"),
            array("timezone"=>"+01:00","region"=>"Europe","subregion"=>"Western Europe","name"=>"Switzerland","alpha2Code"=>"CH","alpha3Code"=>"CHE"),
            array("timezone"=>"+02:00","region"=>"Asia","subregion"=>"Western Asia","name"=>"Syria","alpha2Code"=>"SY","alpha3Code"=>"SYR"),
            array("timezone"=>"+08:00","region"=>"Asia","subregion"=>"Eastern Asia","name"=>"Taiwan","alpha2Code"=>"TW","alpha3Code"=>"TWN"),
            array("timezone"=>"+05:00","region"=>"Asia","subregion"=>"Central Asia","name"=>"Tajikistan","alpha2Code"=>"TJ","alpha3Code"=>"TJK"),
            array("timezone"=>"+03:00","region"=>"Africa","subregion"=>"Eastern Africa","name"=>"Tanzania","alpha2Code"=>"TZ","alpha3Code"=>"TZA"),
            array("timezone"=>"+07:00","region"=>"Asia","subregion"=>"South-Eastern Asia","name"=>"Thailand","alpha2Code"=>"TH","alpha3Code"=>"THA"),
            array("timezone"=>"+09:00","region"=>"Asia","subregion"=>"South-Eastern Asia","name"=>"East Timor","alpha2Code"=>"TL","alpha3Code"=>"TLS"),
            array("timezone"=>"+00:00","region"=>"Africa","subregion"=>"Western Africa","name"=>"Togo","alpha2Code"=>"TG","alpha3Code"=>"TGO"),
            array("timezone"=>"+13:00","region"=>"Oceania","subregion"=>"Polynesia","name"=>"Tokelau","alpha2Code"=>"TK","alpha3Code"=>"TKL"),
            array("timezone"=>"+13:00","region"=>"Oceania","subregion"=>"Polynesia","name"=>"Tonga","alpha2Code"=>"TO","alpha3Code"=>"TON"),
            array("timezone"=>"-04:00","region"=>"Americas","subregion"=>"Caribbean","name"=>"Trinidad and Tobago","alpha2Code"=>"TT","alpha3Code"=>"TTO"),
            array("timezone"=>"+01:00","region"=>"Africa","subregion"=>"Northern Africa","name"=>"Tunisia","alpha2Code"=>"TN","alpha3Code"=>"TUN"),
            array("timezone"=>"+02:00","region"=>"Asia","subregion"=>"Western Asia","name"=>"Turkey","alpha2Code"=>"TR","alpha3Code"=>"TUR"),
            array("timezone"=>"+05:00","region"=>"Asia","subregion"=>"Central Asia","name"=>"Turkmenistan","alpha2Code"=>"TM","alpha3Code"=>"TKM"),
            array("timezone"=>"-04:00","region"=>"Americas","subregion"=>"Caribbean","name"=>"Turks and Caicos Islands","alpha2Code"=>"TC","alpha3Code"=>"TCA"),
            array("timezone"=>"+12:00","region"=>"Oceania","subregion"=>"Polynesia","name"=>"Tuvalu","alpha2Code"=>"TV","alpha3Code"=>"TUV"),
            array("timezone"=>"+03:00","region"=>"Africa","subregion"=>"Eastern Africa","name"=>"Uganda","alpha2Code"=>"UG","alpha3Code"=>"UGA"),
            array("timezone"=>"+02:00","region"=>"Europe","subregion"=>"Eastern Europe","name"=>"Ukraine","alpha2Code"=>"UA","alpha3Code"=>"UKR"),
            array("timezone"=>"+04:00","region"=>"Asia","subregion"=>"Western Asia","name"=>"United Arab Emirates","alpha2Code"=>"AE","alpha3Code"=>"ARE"),
            array("timezone"=>"-08:00","region"=>"Europe","subregion"=>"Northern Europe","name"=>"United Kingdom","alpha2Code"=>"GB","alpha3Code"=>"GBR"),
            array("timezone"=>"-12:00","region"=>"Americas","subregion"=>"Northern America","name"=>"United States","alpha2Code"=>"US","alpha3Code"=>"USA"),
            array("timezone"=>"-03:00","region"=>"Americas","subregion"=>"South America","name"=>"Uruguay","alpha2Code"=>"UY","alpha3Code"=>"URY"),
            array("timezone"=>"+05:00","region"=>"Asia","subregion"=>"Central Asia","name"=>"Uzbekistan","alpha2Code"=>"UZ","alpha3Code"=>"UZB"),
            array("timezone"=>"+11:00","region"=>"Oceania","subregion"=>"Melanesia","name"=>"Vanuatu","alpha2Code"=>"VU","alpha3Code"=>"VUT"),
            array("timezone"=>"-04:30","region"=>"Americas","subregion"=>"South America","name"=>"Venezuela","alpha2Code"=>"VE","alpha3Code"=>"VEN"),
            array("timezone"=>"+07:00","region"=>"Asia","subregion"=>"South-Eastern Asia","name"=>"Vietnam","alpha2Code"=>"VN","alpha3Code"=>"VNM"),
            array("timezone"=>"+12:00","region"=>"Oceania","subregion"=>"Polynesia","name"=>"Wallis and Futuna","alpha2Code"=>"WF","alpha3Code"=>"WLF"),
            array("timezone"=>"+00:00","region"=>"Africa","subregion"=>"Northern Africa","name"=>"Western Sahara","alpha2Code"=>"EH","alpha3Code"=>"ESH"),
            array("timezone"=>"+03:00","region"=>"Asia","subregion"=>"Western Asia","name"=>"Yemen","alpha2Code"=>"YE","alpha3Code"=>"YEM"),
            array("timezone"=>"+02:00","region"=>"Africa","subregion"=>"Eastern Africa","name"=>"Zambia","alpha2Code"=>"ZM","alpha3Code"=>"ZMB"),
            array("timezone"=>"+02:00","region"=>"Africa","subregion"=>"Eastern Africa","name"=>"Zimbabwe","alpha2Code"=>"ZW","alpha3Code"=>"ZWE"),
        );

        DB::table('countries')->insert($countries);
    }
}
