<?php

use Illuminate\Database\Seeder;

class TranslateTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('translate_names')->truncate();
        $market = array(
            array(
                'id' => 1,
                'original' => '11번가',
                'chinese' => '11街',
                'korean' => '11번가',
                'english' => '11st',
            ),
            array(
                'id' => 2,
                'original' => 'Gmarket',
                'chinese' => 'G-市场',
                'korean' => '지마켓',
                'english' => 'Gmarket',
            ),
            array(
                'id' => 3,
                'original' => 'Auction',
                'chinese' => '拍卖',
                'korean' => '옥션',
                'english' => 'Auction',
            ),
            array(
                'id' => 4,
                'origin' => '관리자 미 승인 상품',
                'english' => 'notConfirm',
                'korean' => "관리자 미 승인 상품",
                'chinese' => "我们的产品经理批准",
            ),
            array(
                'id' => 5,
                'origin' => '판매 진행 상품',
                'english' => 'confirm',
                'korean' => "판매 진행 상품",
                'chinese' => "产品销售收入",
            ),
            array(
                'id' => 6,
                'origin' => '판매 종료 상품',
                'english' => 'terminate',
                'korean' => "판매 종료 상품",
                'chinese' => "停产产品",
            ),
            array(
                'id' => 7,
                'origin' => '주문 완료',
                'english' => 'orderComplete',
                'korean' => "주문 완료",
                'chinese' => "为了完成",
            ),
            array(
                'id' => 8,
                'origin' => '주문 취소',
                'english' => 'orderCancel',
                'korean' => "주문 취소",
                'chinese' => "订单取消",
            ),
            array(
                'id' => 9,
                'origin' => '결제 완료',
                'english' => 'paymentComplete',
                'korean' => "결제 완료",
                'chinese' => "完成支付",
            ),
            array(
                'id' => 10,
                'origin' => '결제 취소',
                'english' => 'paymentCancel',
                'korean' => "결제 취소",
                'chinese' => "付款已取消",
            ),
            array(
                'id' => 11,
                'origin' => '배송 준비중',
                'english' => 'shippingPreparation',
                'korean' => "배송 준비중",
                'chinese' => "装运准备",
            ),
            array(
                'id' => 12,
                'origin' => '배송 중',
                'english' => 'shipping',
                'korean' => "배송 중",
                'chinese' => "交付",
            ),
            array(
                'id' => 13,
                'origin' => '배송 완료',
                'english' => 'shippingComplete',
                'korean' => "배송 완료",
                'chinese' => "运",
            ),
            array(
                'id' => 14,
                'origin' => '구매 확정',
                'english' => 'purchaseConfirm',
                'korean' => "구매 확정",
                'chinese' => "购买确认",
            ),
            array(
                'id' => 15,
                'origin' => '환불 신청',
                'english' => 'refundApplication',
                'korean' => "환불 신청",
                'chinese' => "退",
            ),
            array(
                'id' => 16,
                'origin' => '환불 완료',
                'english' => 'refundComplete',
                'korean' => "환불 완료",
                'chinese' => "退款",
            ),
            array(
                'id' => 17,
                'origin' => '남녀공용',
                'english' => 'unisex',
                'korean' => "남녀공용",
                'chinese' => "男女皆宜的",
            ),
            array(
                'id' => 18,
                'origin' => '남성용',
                'english' => 'male',
                'korean' => "남성용",
                'chinese' => "只有男人",
            ),
            array(
                'id' => 19,
                'origin' => '여성용',
                'english' => 'female',
                'korean' => "여성용",
                'chinese' => "只有女人",
            ),
            array(
                'id' => 20,
                'origin' => 'KRW',
                'english' => 'won',
                'korean' => "원",
                'chinese' => "韩元",
            ),
            array(
                'id' => 21,
                'origin' => 'CNY',
                'english' => 'rmb',
                'korean' => "위안",
                'chinese' => "人民幣",
            ),
            array(
                'id' => 22,
                'origin' => 'USD',
                'english' => 'dollar',
                'korean' => "달러",
                'chinese' => "美元",
            ),
            array(
                'id' => 23,
                'origin' => '쿠팡',
                'english' => 'coopang',
                'korean' => "쿠팡",
                'chinese' => "coopang",
            ),
            [
                "id" => 24,
                "original" => "패션의류",
                "chinese" => "服装",
                "korean" => null,
                "english" => null,
            ],
            [
                "id" => 25,
                "original" => "패션잡화",
                "chinese" => "杂货",
                "korean" => null,
                "english" => null,
            ],
            [
                "id" => 26,
                "original" => "화장품/미용",
                "chinese" => "化妆品/美容",
                "korean" => null,
                "english" => null,
            ],
            [
                "id" => 27,
                "original" => "디지털/가전",
                "chinese" => "数码/家电",
                "korean" => null,
                "english" => null,
            ],
            [
                "id" => 28,
                "original" => "가구/인테리어",
                "chinese" => "家具/室内装饰",
                "korean" => null,
                "english" => null,
            ],
            [
                "id" => 29,
                "original" => "출산/육아",
                "chinese" => "生育/育儿",
                "korean" => null,
                "english" => null,
            ],
            [
                "id" => 30,
                "original" => "식품",
                "chinese" => "食品",
                "korean" => null,
                "english" => null,
            ],
            [
                "id" => 31,
                "original" => "스포츠/레저",
                "chinese" => "运动/休闲",
                "korean" => null,
                "english" => null,
            ],
            [
                "id" => 32,
                "original" => "생활/건강",
                "chinese" => "生活/健康",
                "korean" => null,
                "english" => null,
            ],
            [
                "id" => 33,
                "original" => "여행/문화",
                "chinese" => "旅游/文化",
                "korean" => null,
                "english" => null,
            ],
            [
                "id" => 34,
                "original" => "여성의류",
                "chinese" => "女装",
                "korean" => null,
                "english" => null,
            ],
            [
                "id" => 35,
                "original" => "남성의류",
                "chinese" => "男装",
                "korean" => null,
                "english" => null,
            ],
            [
                "id" => 36,
                "original" => "아동의류",
                "chinese" => "童装",
                "korean" => null,
                "english" => null,
            ],
            [
                "id" => 37,
                "original" => "여성언더웨어/잠옷",
                "chinese" => "女内衣/睡衣",
                "korean" => null,
                "english" => null,
            ],
            [
                "id" => 38,
                "original" => "남성언더웨어/잠옷",
                "chinese" => "男内衣/睡衣",
                "korean" => null,
                "english" => null,
            ],
            [
                "id" => 39,
                "original" => "아동언더웨어/잠옷",
                "chinese" => "儿童内衣/睡衣",
                "korean" => null,
                "english" => null,
            ],
            [
                "id" => 40,
                "original" => "여성신발",
                "chinese" => "女鞋",
                "korean" => null,
                "english" => null,
            ],
            [
                "id" => 41,
                "original" => "남성신발",
                "chinese" => "男鞋",
                "korean" => null,
                "english" => null,
            ],
            [
                "id" => 42,
                "original" => "여성가방",
                "chinese" => "女包",
                "korean" => null,
                "english" => null,
            ],
            [
                "id" => 43,
                "original" => "남성가방",
                "chinese" => "男包",
                "korean" => null,
                "english" => null,
            ],
            [
                "id" => 44,
                "original" => "여행용 가방/소품",
                "chinese" => "旅行包/旅行用品",
                "korean" => null,
                "english" => null,
            ],
            [
                "id" => 45,
                "original" => "지갑",
                "chinese" => "钱包",
                "korean" => null,
                "english" => null,
            ],
            [
                "id" => 46,
                "original" => "시계",
                "chinese" => "表",
                "korean" => null,
                "english" => null,
            ],
            [
                "id" => 47,
                "original" => "주얼리",
                "chinese" => "配饰",
                "korean" => null,
                "english" => null,
            ],
            [
                "id" => 48,
                "original" => "모자",
                "chinese" => "帽子",
                "korean" => null,
                "english" => null,
            ],
            [
                "id" => 49,
                "original" => "기타잡화",
                "chinese" => "其他杂货",
                "korean" => null,
                "english" => null,
            ],
            [
                "id" => 50,
                "original" => "스킨케어",
                "chinese" => "面部护肤",
                "korean" => null,
                "english" => null,
            ],
            [
                "id" => 51,
                "original" => "선케어",
                "chinese" => "防晒",
                "korean" => null,
                "english" => null,
            ],
            [
                "id" => 52,
                "original" => "베이스메이크업",
                "chinese" => "打底装",
                "korean" => null,
                "english" => null,
            ],
            [
                "id" => 53,
                "original" => "색조메이크업",
                "chinese" => "彩妆",
                "korean" => null,
                "english" => null,
            ],
            [
                "id" => 54,
                "original" => "클렌징",
                "chinese" => "洁面",
                "korean" => null,
                "english" => null,
            ],
            [
                "id" => 55,
                "original" => "마스크/팩",
                "chinese" => "面膜",
                "korean" => null,
                "english" => null,
            ],
            [
                "id" => 56,
                "original" => "헤어케어",
                "chinese" => "护发",
                "korean" => null,
                "english" => null,
            ],
            [
                "id" => 57,
                "original" => "헤어스타일링",
                "chinese" => "发型",
                "korean" => null,
                "english" => null,
            ],
            [
                "id" => 58,
                "original" => "바디케어",
                "chinese" => "身体护肤",
                "korean" => null,
                "english" => null,
            ],
            [
                "id" => 59,
                "original" => "네일케어",
                "chinese" => "美甲护理",
                "korean" => null,
                "english" => null,
            ],
            [
                "id" => 60,
                "original" => "남성화장품",
                "chinese" => "男士化妆品",
                "korean" => null,
                "english" => null,
            ],
            [
                "id" => 61,
                "original" => "향수",
                "chinese" => "香水",
                "korean" => null,
                "english" => null,
            ],
            [
                "id" => 62,
                "original" => "뷰티소품",
                "chinese" => "美容道具",
                "korean" => null,
                "english" => null,
            ],
            [
                "id" => 63,
                "original" => "휴대폰",
                "chinese" => "手机",
                "korean" => null,
                "english" => null,
            ],
            [
                "id" => 64,
                "original" => "카메라/캠코더 용품",
                "chinese" => "照相机/摄像机用品",
                "korean" => null,
                "english" => null,
            ],
            [
                "id" => 65,
                "original" => "영상가전",
                "chinese" => "影像家电",
                "korean" => null,
                "english" => null,
            ],
            [
                "id" => 66,
                "original" => "생활가전",
                "chinese" => "生活家电",
                "korean" => null,
                "english" => null,
            ],
            [
                "id" => 67,
                "original" => "주방가전",
                "chinese" => "厨房家电",
                "korean" => null,
                "english" => null,
            ],
            [
                "id" => 68,
                "original" => "휴대폰 액세서리",
                "chinese" => "手机小品",
                "korean" => null,
                "english" => null,
            ],
            [
                "id" => 69,
                "original" => "게임/타이틀",
                "chinese" => "游戏/游戏机",
                "korean" => null,
                "english" => null,
            ],
            [
                "id" => 70,
                "original" => "음향가전",
                "chinese" => "音响设备",
                "korean" => null,
                "english" => null,
            ],
            [
                "id" => 71,
                "original" => "이미용가전",
                "chinese" => "美容家电",
                "korean" => null,
                "english" => null,
            ],
            [
                "id" => 72,
                "original" => "계절가전",
                "chinese" => "季节家电",
                "korean" => null,
                "english" => null,
            ],
            [
                "id" => 73,
                "original" => "노트북",
                "chinese" => "笔记本电脑",
                "korean" => null,
                "english" => null,
            ],
            [
                "id" => 74,
                "original" => "태블릿PC",
                "chinese" => "平板电脑",
                "korean" => null,
                "english" => null,
            ],
            [
                "id" => 75,
                "original" => "PC",
                "chinese" => "PC",
                "korean" => null,
                "english" => null,
            ],
            [
                "id" => 76,
                "original" => "모니터",
                "chinese" => "显示器",
                "korean" => null,
                "english" => null,
            ],
            [
                "id" => 77,
                "original" => "저장장치",
                "chinese" => "存储器",
                "korean" => null,
                "english" => null,
            ],
            [
                "id" => 78,
                "original" => "네트워크 장비",
                "chinese" => "网络设备",
                "korean" => null,
                "english" => null,
            ],
            [
                "id" => 79,
                "original" => "PC 주변기기",
                "chinese" => "PC外部设备",
                "korean" => null,
                "english" => null,
            ],
            [
                "id" => 80,
                "original" => "자동차기기",
                "chinese" => "汽车机器",
                "korean" => null,
                "english" => null,
            ]
        );

        DB::table('translate_names')->insert($market);
    }
}
